### ISSUE TITLE
Cannot install lisk on server

### ISSUE THREAD

**Issue by KarolosLykos** [LiskHQ/lisk-build#248]
Hi, I am trying to set a node on my server ,

I am getting this error:

`X Failed to create Postgresql user.`

But in the ` installLisk.out` I cannot find any more info .

I completely removed postgresql and then reinstalled it I created a role with my username but still getting this error.

I can't find anything useful thank you for your time

**Comment by Nazgolze** [comment]
Hi Karolos,

That can happen I think if there's already a postgres user. Try
uninstalling PostgreSQL and with it installed, run installLisk.sh

On Dec 22, 2017 12:02 PM, "Karolos Lykos" <notifications@github.com> wrote:

Hi, I am trying to set a node on my server ,

I am getting this error:

X Failed to create Postgresql user.

But in the installLisk.out I cannot find any more info .

I completely removed postgresql and then reinstalled it I created a role
with my username but still getting this error.

I can't find anything useful thank you for your time

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LiskHQ/lisk-build/issues/248>, or mute the thread

**Comment by Nazgolze** [comment]
With it *uninstalled - sorry for the confusion

**Comment by KarolosLykos** [comment]
*thank you for your help
I completely remove postgres I tried installing list again .

```bash
dpkg -l | grep postgres
ii  postgresql                    9.5+173ubuntu0.1                   all          object-relational SQL database (supported version)
ii  postgresql-9.5                9.5.10-0ubuntu0.16.04              amd64        object-relational SQL database, version 9.5 server
ii  postgresql-client-9.5         9.5.10-0ubuntu0.16.04              amd64        front-end programs for PostgreSQL 9.5
ii  postgresql-client-common      173ubuntu0.1                       all          manager for multiple PostgreSQL client versions
ii  postgresql-common             173ubuntu0.1                       all          PostgreSQL database-cluster manager
ii  postgresql-contrib            9.5+173ubuntu0.1                   all          additional facilities for PostgreSQL (supported version)
ii  postgresql-contrib-9.5        9.5.10-0ubuntu0.16.04              amd64        additional facilities for PostgreSQL
```

```bash
 sudo apt-get --purge remove postgresql postgresql-9.5  postgresql-client  postgresql-client-9.5 postgresql-client-common postgresql-common  postgresql-contrib postgresql-contrib-9.5
```

```bash
sudo rm -rf /var/lib/postgresql/
sudo rm -rf /var/log/postgresql/
sudo rm -rf /etc/postgresql/
````

```bash
bash installLisk.sh install -r main
```

Still getting the same error : 

```bash
Coldstarting Lisk for the first time
√ Postgresql is running.
X Failed to create Postgresql user.
Installation failed. Cleaning up...

Stopping Lisk components before cleanup
√ Lisk stopped successfully.
X Postgresql failed to stop.
√ Postgresql Killed.
```

**Comment by ghost** [comment]
@kariolos It looks like you're not using the latest version of `installLisk.sh`. Please follow the [documentation](https://docs.lisk.io/docs/core-installation-binary-main) to download and execute the latest version. Should you still encounter issues please provide more information (where did you get the installation script from, what did you execute and the full output including error message).
