### ISSUE TITLE
built in script to backup database

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-build#30]
Courtesy of: @ByronAP

> It would be nice if there was a built in script we could run that would cc the current db and also a restore command. This would make it possible to restore from a local copy instead of downloading the entire chain from peers or bootstrap. This shouldn't be too hard as the script can stop Lisk and then restart it once the operation is complete.

**Comment by karmacoma** [comment]
There is a new snapshot facility to be introduced in 0.3.2. To use it you simply add the following command switch when starting the client, putting it in a snapshot mode.

```
node app.js --snapshot <round>
```

e.g. to verify the blockchain up to end of round 1000:

```
node app.js --snapshot 1000
```

Any blocks after round 1000 will be deleted, including all transactions. This allows snapshots to be open cleanly onto next round, with votes closed off from previous round. Once verification is complete the client will shutdown immediately at this point, allowing you to take a database snapshot using `pg_dump`.

**Comment by fix** [comment]
@Isabello @karmacoma Can we close it now? It sounds fully implemented now

**Comment by karmacoma** [comment]
@fix Not yet. The snapshotting element of it is done, but an actual script to backup / restore the database is not.

**Comment by Isabello** [comment]
isabella [10:53 AM]  
automated snapshot process

A packaged config.json for snapshots will be required. Its changes would include: port, db name, log names

ex
port: 9000
db name: lisk_snapshot
log name:  lisk_snapshot.log

In uptime we will clone the database from the active instance to the lisk_snapshot database.

Lisk will start another instance in snapshot mode using a `-c` flag for the new config.json. Subsequent to that, the script will monitor the logs for successful completion and perform a database query to ensure that the process is ending at the expected block height, otherwise the result is thrown out.

Once success is positively indicated a new export is taken and marked as good. this will be stored in a location specified by the user or by default in $LISK_HOME/backups

Other things to do after snapshot is verified
- Delete peers
- Dump snapshot with no owner `-O` 

overall with this method we can allow users to maintain their own snapshots and reduce the need for a centralized snapshot

Use of these snapshots:
When users go to rebuild they will be able to pass the flag `-r` or `-f` and a file name, this way rebuild would bypass remote snaps and use one the user has saved locally.

**Comment by Isabello** [comment]
This is now satisfied by #36
