### ISSUE TITLE
installLisk.sh upgrade remove/overwrite previous config

### ISSUE THREAD

**Issue by ghost** [LiskHQ/lisk-build#34]
installLisk.sh upgrade indirectly caused blockchain fork:3 i guess. Since i have did upgrade before, backup directory has been already created and i couldn't upgrade again due error with mkdir, there should be check if backup directory already exists to remove it or not.
Also i have noticed that i can upgrade the same version and it will always remove current lisk and install again (the same version) there should be check if current version matches or not latest released.

Not sure if this is correct repo, but couldn't find repository with this script.

**Comment by Isabello** [comment]
upgrade is still in the early stages of testing. The documentation page for upgrading Lisk clearly states to use only the installation procedure and not the upgrade procedure. In the future this functionality will be leverage this function in order to preserve database state since Blockchain Apps are installed into the database. This configuration would be lost with a full reinstall and will be needed in the future.

As for checking if its the same version, this is unnecessary. installLisk.sh is only used to provision the solution and its up to users to be aware of their own system and state of Lisk when using this utility.

**Comment by Isabello** [comment]
resolved by commit

https://github.com/LiskHQ/lisk-build/commit/1e646222bf861e06381cea0af9138c9b1728cf0e
