### ISSUE TITLE
"upgrade" function in installLisk.sh is broken

### ISSUE THREAD

**Issue by ghost** [LiskHQ/lisk-build#55]
After upgrading to 0.4.1 to 0.5.0, 3/3 servers couldn't be upgraded using this feature in script.
First and Second node resulted with corrupted database, database name and/or username was invalid, it couldn't fix itself after rebuild or/and coldstart.

Third resulted in missing "blocks" table, it also couldn't be repaired with lisk.sh or installLisk.sh.

After removing all files related to Lisk on each server and doing clean install everything is working fine.

**Comment by Isabello** [comment]
upgrading from 0.4.1 is risky because of the block processing inconsistency, this is a wont-fix issue since 0.5.0 has all of the required fixes for preserving the tables.

additionally, the format in config.json changed for db user. customization of this param will need to be handled on a per user install basis if its different than what we normally expect.

**Comment by Isabello** [comment]
this issue should be resolved by improvements to the upgrade process by this commit: 60bfab7622d0ddc3986f7306e678c02db4983f93
